package store

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib" // Postgres (Supabase)
)

type Store struct {
	db *sql.DB
}

// Open 은 config.json 의 Supabase 연결 문자열로 접속한다.
// 서버에 데이터가 하나도 없고 이전 버전의 로컬 SQLite 파일(sobi.db)이 있으면
// 그 데이터를 자동으로 Supabase 로 옮긴 뒤 시작한다.
func Open() (*Store, error) {
	cfg, err := LoadConfig()
	if err != nil {
		return nil, err
	}
	s, err := OpenAt(cfg.DatabaseURL)
	if err != nil {
		return nil, err
	}

	empty, err := s.isEmpty()
	if err != nil {
		s.Close()
		return nil, err
	}
	if empty {
		legacy, lerr := LegacySQLitePath()
		if lerr == nil {
			if _, statErr := os.Stat(legacy); statErr == nil {
				if merr := s.migrateFromSQLite(legacy); merr != nil {
					s.Close()
					return nil, fmt.Errorf("로컬 데이터를 Supabase 로 옮기는 중 오류: %w", merr)
				}
				empty = false
			}
		}
	}
	if empty {
		if err := s.seedDefaults(); err != nil {
			s.Close()
			return nil, err
		}
	}
	if err := s.seedPaymentMethods(); err != nil {
		s.Close()
		return nil, err
	}
	// "식비/배달" 처럼 슬래시로 계층을 흉내낸 이름을 주/부 계층으로 정리한다(한 번만 효과).
	if err := s.splitSlashCategories(); err != nil {
		s.Close()
		return nil, err
	}
	return s, nil
}

// OpenAt 은 Postgres 연결 문자열로 접속하고 스키마만 준비한다. (시드 없음)
func OpenAt(dsn string) (*Store, error) {
	db, err := sql.Open("pgx", normalizeDSN(dsn))
	if err != nil {
		return nil, err
	}
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	if err := db.PingContext(ctx); err != nil {
		db.Close()
		return nil, fmt.Errorf("Supabase 접속 실패: %w", err)
	}
	s := &Store{db: db}
	if err := s.migrate(); err != nil {
		db.Close()
		return nil, err
	}
	return s, nil
}

func (s *Store) Close() error { return s.db.Close() }

func (s *Store) migrate() error {
	schema := `
CREATE TABLE IF NOT EXISTS members (
	id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS categories (
	id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	kind TEXT NOT NULL DEFAULT 'expense' CHECK (kind IN ('income','expense','transfer'))
);
-- 주/부 2단 계층: parent_id NULL 이면 주(대분류), 값이 있으면 그 주의 부(소분류).
ALTER TABLE categories ADD COLUMN IF NOT EXISTS parent_id BIGINT REFERENCES categories(id) ON DELETE SET NULL;
-- 표시 순서: 같은 그룹(같은 종류의 주끼리, 또는 같은 주 아래 부끼리) 안에서 오름차순.
ALTER TABLE categories ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;
-- 순서를 처음 도입할 때 한 번만: 지금 보이는 순서(이름 가나다)를 그대로 굳혀 둔다.
-- 이미 순서를 만진 DB(0 아닌 값이 하나라도 있음)에서는 아무 것도 하지 않는다.
UPDATE categories c SET sort_order = x.rn
FROM (
	SELECT id, ROW_NUMBER() OVER (
		PARTITION BY COALESCE(parent_id, 0), kind ORDER BY name
	) - 1 AS rn
	FROM categories
) x
WHERE c.id = x.id
  AND (SELECT COUNT(*) FROM categories WHERE sort_order <> 0) = 0
  AND (SELECT COUNT(*) FROM categories) > 1;
-- 이름은 같은 주 안에서만 유일하면 된다 (예: 식비>배달 과 쇼핑>배달 공존 허용).
ALTER TABLE categories DROP CONSTRAINT IF EXISTS categories_name_key;
CREATE UNIQUE INDEX IF NOT EXISTS categories_parent_name ON categories(COALESCE(parent_id, 0), name);
CREATE TABLE IF NOT EXISTS payment_methods (
	id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name            TEXT NOT NULL UNIQUE,
	type            TEXT NOT NULL DEFAULT 'card' CHECK (type IN ('card','cash','bank')),
	issuer          TEXT NOT NULL DEFAULT '',
	billing_day     INTEGER NOT NULL DEFAULT 0,
	cycle_start_day INTEGER NOT NULL DEFAULT 1,
	perf_target     BIGINT NOT NULL DEFAULT 0,
	color           TEXT NOT NULL DEFAULT ''
);
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS color TEXT NOT NULL DEFAULT '';
-- 캐시백 설정. 요율은 만분율(bp)로 담는다: 1% = 100bp (소수점 요율도 정수로 정확히 표현).
-- cashback_bonus_days 안에 카드대금을 갚은 결제에는 bonus 요율을 한 번 더 얹는다.
-- 카드 혜택 자료(카드사 안내 기준). 실적 조건은 기존 perf_target 을 그대로 쓴다.
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS annual_fee BIGINT NOT NULL DEFAULT 0;
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS annual_fee_global BIGINT NOT NULL DEFAULT 0;
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS benefit_url TEXT NOT NULL DEFAULT '';
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS benefit_note TEXT NOT NULL DEFAULT '';
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS cashback_bp INTEGER NOT NULL DEFAULT 0;
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS cashback_bonus_bp INTEGER NOT NULL DEFAULT 0;
ALTER TABLE payment_methods ADD COLUMN IF NOT EXISTS cashback_bonus_days INTEGER NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS transactions (
	id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	date              TEXT NOT NULL,
	amount            BIGINT NOT NULL,
	direction         TEXT NOT NULL DEFAULT 'expense' CHECK (direction IN ('income','expense','transfer')),
	merchant          TEXT NOT NULL DEFAULT '',
	memo              TEXT NOT NULL DEFAULT '',
	member_id         BIGINT REFERENCES members(id) ON DELETE SET NULL,
	category_id       BIGINT REFERENCES categories(id) ON DELETE SET NULL,
	payment_method_id BIGINT REFERENCES payment_methods(id) ON DELETE SET NULL,
	source            TEXT NOT NULL DEFAULT 'manual',
	auto_classified   INTEGER NOT NULL DEFAULT 0,
	created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- 세금·공과금처럼 카드사가 실적에 넣어주지 않는 결제를 실적 계산에서만 빼기 위한 표시.
-- 일반 지출 집계에는 그대로 포함된다(실제로 나간 돈은 맞으므로).
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS exclude_perf INTEGER NOT NULL DEFAULT 0;
-- 카드대금을 언제 갚았는지("YYYY-MM-DD", 빈 값이면 미납부).
-- 결제일로부터 카드가 정한 기한 안에 갚으면 추가 캐시백을 받는 카드가 있어 그 판정에 쓴다.
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS paid_at TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_tx_date ON transactions(date);
CREATE TABLE IF NOT EXISTS rules (
	id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	merchant    TEXT NOT NULL,
	amount_min  BIGINT NOT NULL,
	amount_max  BIGINT NOT NULL,
	member_id   BIGINT REFERENCES members(id) ON DELETE CASCADE,
	category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
	label       TEXT NOT NULL DEFAULT ''
);
-- 카드 혜택 항목. 카드사 안내를 그대로 옮겨 적는 자료용 표라, 요율은 "최대" 표기와
-- 미확인 여부를 함께 남길 수 있게 한다(실적 구간에 따라 달라지는 경우가 많다).
CREATE TABLE IF NOT EXISTS card_benefits (
	id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	payment_method_id BIGINT NOT NULL REFERENCES payment_methods(id) ON DELETE CASCADE,
	area              TEXT NOT NULL,
	kind              TEXT NOT NULL DEFAULT 'point' CHECK (kind IN ('point','discount','service')),
	rate_bp           INTEGER NOT NULL DEFAULT 0,
	is_max            INTEGER NOT NULL DEFAULT 0,
	monthly_cap       BIGINT NOT NULL DEFAULT 0,
	note              TEXT NOT NULL DEFAULT '',
	needs_check       INTEGER NOT NULL DEFAULT 0,
	sort_order        INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_card_benefits_pm ON card_benefits(payment_method_id);
CREATE TABLE IF NOT EXISTS budgets (
	id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
	ym          TEXT NOT NULL DEFAULT '*',
	amount      BIGINT NOT NULL
);
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS ym TEXT NOT NULL DEFAULT '*';
ALTER TABLE budgets DROP CONSTRAINT IF EXISTS budgets_category_id_key;
CREATE UNIQUE INDEX IF NOT EXISTS budgets_cat_ym ON budgets(category_id, ym);
-- 직접 등록해 관리하는 정기결제(구독·고정비). 거래를 만들지는 않고 실제 거래와 대조만 한다.
CREATE TABLE IF NOT EXISTS subscriptions (
	id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name              TEXT NOT NULL,
	merchant          TEXT NOT NULL DEFAULT '',
	amount            BIGINT NOT NULL DEFAULT 0,
	cycle             TEXT NOT NULL DEFAULT 'monthly' CHECK (cycle IN ('monthly','yearly')),
	billing_day       INTEGER NOT NULL DEFAULT 1,
	billing_month     INTEGER NOT NULL DEFAULT 0,
	start_ym          TEXT NOT NULL DEFAULT '',
	end_ym            TEXT NOT NULL DEFAULT '',
	next_amount       BIGINT NOT NULL DEFAULT 0,
	next_amount_ym    TEXT NOT NULL DEFAULT '',
	category_id       BIGINT REFERENCES categories(id) ON DELETE SET NULL,
	member_id         BIGINT REFERENCES members(id) ON DELETE SET NULL,
	payment_method_id BIGINT REFERENCES payment_methods(id) ON DELETE SET NULL,
	memo              TEXT NOT NULL DEFAULT '',
	active            INTEGER NOT NULL DEFAULT 1
);
`
	_, err := s.db.Exec(schema)
	return err
}

func (s *Store) isEmpty() (bool, error) {
	var n int
	if err := s.queryRow(`SELECT COUNT(*) FROM members`).Scan(&n); err != nil {
		return false, err
	}
	return n == 0, nil
}

// seedDefaults 는 새 DB에 기본 귀속자/카테고리를 채운다.
func (s *Store) seedDefaults() error {
	for _, m := range []string{"아빠", "엄마", "아이", "공동"} {
		if _, err := s.exec(`INSERT INTO members(name) VALUES(?) ON CONFLICT (name) DO NOTHING`, m); err != nil {
			return err
		}
	}
	cats := []struct{ name, kind string }{
		{"급여", "income"}, {"기타수입", "income"},
		{"통신비", "expense"}, {"식비", "expense"}, {"교육비", "expense"},
		{"대출상환", "expense"}, {"회비/경조사", "expense"}, {"생활용품", "expense"},
		{"교통/차량", "expense"}, {"의료비", "expense"}, {"문화/여가", "expense"},
		{"기타지출", "expense"},
		{"투자이체", "transfer"}, {"저축", "transfer"},
	}
	for i, c := range cats {
		// 카테고리 이름은 주 단위로만 유일하므로 ON CONFLICT(name) 대신 존재 확인으로 넣는다.
		// sort_order 는 위 목록 순서를 그대로 쓴다(가나다보다 이 순서가 읽기 좋다).
		if _, err := s.exec(`
INSERT INTO categories(name, kind, sort_order) SELECT ?, ?, ?
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = ? AND parent_id IS NULL)`,
			c.name, c.kind, i, c.name); err != nil {
			return err
		}
	}
	return nil
}

// seedPaymentMethods 는 기본 결제수단(카드/현금/계좌이체)이 빠져 있으면 보충한다.
func (s *Store) seedPaymentMethods() error {
	pms := []struct{ name, typ string }{
		{"카드", "card"}, {"현금", "cash"}, {"계좌이체", "bank"},
	}
	for _, p := range pms {
		if _, err := s.exec(`INSERT INTO payment_methods(name, type) VALUES(?,?) ON CONFLICT (name) DO NOTHING`, p.name, p.typ); err != nil {
			return err
		}
	}
	return nil
}

func (s *Store) DB() *sql.DB { return s.db }

// EnsureDefaults 는 기본 구성원/카테고리/결제수단을 채운다. (초기화/테스트용)
func (s *Store) EnsureDefaults() error {
	if err := s.seedDefaults(); err != nil {
		return err
	}
	return s.seedPaymentMethods()
}

// pq 는 SQLite 식 ? 플레이스홀더를 Postgres 식 $1, $2... 로 바꾼다.
func pq(query string) string {
	if !strings.ContainsRune(query, '?') {
		return query
	}
	var b strings.Builder
	n := 0
	for _, r := range query {
		if r == '?' {
			n++
			b.WriteString("$" + strconv.Itoa(n))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func (s *Store) exec(query string, args ...interface{}) (sql.Result, error) {
	return s.db.Exec(pq(query), args...)
}

func (s *Store) query(query string, args ...interface{}) (*sql.Rows, error) {
	return s.db.Query(pq(query), args...)
}

func (s *Store) queryRow(query string, args ...interface{}) *sql.Row {
	return s.db.QueryRow(pq(query), args...)
}

// likeEscape 는 LIKE/ILIKE 패턴의 특수문자(\ % _)를 이스케이프한다(기본 이스케이프 문자 \).
func likeEscape(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, "%", `\%`)
	s = strings.ReplaceAll(s, "_", `\_`)
	return s
}

func nullableID(p *int64) interface{} {
	if p == nil {
		return nil
	}
	return *p
}

func scanNullableID(v sql.NullInt64) *int64 {
	if !v.Valid {
		return nil
	}
	id := v.Int64
	return &id
}

var ErrNotFound = fmt.Errorf("not found")
